### ISSUE TITLE
Having trouble with installation

### ISSUE THREAD

**Issue by marcoescueta** [devicehive/devicehive-docker#5]
Hello, I have an issue regarding installation. I followed the steps but when I access port 80 firebug outputs and error which is : "NetworkError: 404 Not Found - http://localhost/". Please help as I would need this for my IoT project. Thank you! BTW I'm using Docker for Mac

**Comment by sitnik** [comment]
Hi @marcoescueta.
Sorry for so late response to your request.
I can't say anything about your problem because I'm maintaining this project from mid 2017 and it has changed a lot.
Currently we've reworked most of the DeviceHive core, split it to several services and added lots of features. I hope to hear from you if you want to test new version.
Nevertheless, thank you for reporting!
I'm closing this issue because it's for unsupported version.
